### PR TITLE
Move x86_64-fortanix-unknown-sgx to tier 2

### PR DESCRIPTION
**Pull request by jethrogb**

### CODE REVIEW

**Comment by jethrogb** [comment]
Please merge this as it's mentioned in the 1.33 release notes.

**Comment by lzutao** [comment]
ping @pietroalbini

**Comment by pietroalbini** [comment]
Merging this, but I *really* want to find a better way to manage this list.

**Comment by jethrogb** [comment]
@pietroalbini the information could come from src/librustc_target and src/ci, but storing the right metadata there in a decent format might be... awkward.

**Pull request merged**
