### PR TITLE
Do not validate UTF-8 of RUST_LOG twice

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by kennytm** [comment]
[`env_logger`](https://docs.rs/env_logger/0.7.1/src/env_logger/lib.rs.html#968-972) itself requires UTF-8 though.

**Comment by XAMPPRocky** [comment]
@lzutao Thank you for your PR, Is there a particular reason for this change?

**Comment by lzutao** [comment]
Thank @XAMPPRocky for the question, I wanted to avoid needlessly validating UTF-8-ness of RUST_LOG. But as @kennytm pointed out, `env_logger` itself get the variable from `env::var`.

Now I pass the RUST_LOG directly to `env_logger`, which avoid extra `env::var`.

**Comment by XAMPPRocky** [comment]
Okay, this change seems fine to me. Thank you again for your PR!

**Pull request merged**
