### PR TITLE
Remove the "State of Rust" page

### PR DESCRIPTION
**Pull request by jonas-schievink**
According to @XAMPPRocky, the GitHub project board fully replaces this table. Let's remove it so that there's slightly less outdated content in the forge.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Can you make this a redirect?

**Comment by jonas-schievink** [comment]
Theoretically, I should. However:

* The way to do redirects in Jekyll seems to be `jekyll-redirect-from`, which needs to be put in the `_config.yml`, which gets overwritten by the Rust script
* When using that plugin with `redirect_to: <url>` it produces an infinite redirect loop instead of putting the right url there (the generated page contains `<meta http-equiv="refresh" content="0;URL=''">`)

**Comment by pietroalbini** [comment]
We already have redirects setup on other pages. Take a look at this:

https://raw.githubusercontent.com/rust-lang/rust-forge/master/stabilization-guide.md

**Comment by jonas-schievink** [comment]
That did the trick, thanks!

**Comment by pietroalbini** [comment]
Thanks!

**Pull request merged**
