### PR TITLE
Add "next" row after "nightly"

### PR DESCRIPTION
**Pull request by Centril**
Let's say nightly is 1.43, then "next" is 1.44.

r? @XAMPPRocky

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Looks good to me. I'm going to leave this open for a bit in case someone has particular opinions about it being called next and merge it tomorrow otherwise.

**Comment by pietroalbini** [comment]
Slight opinion torwards "Nightly + 1".

**Comment by Centril** [comment]
Not sure if that "+1" is going to break the javascript. :P

**Comment by Centril** [comment]
But I can just tweak the text instead... and I have done that now.

**Pull request merged**
