### PR TITLE
Add avr-unknown-unknown to platform-support.md

### PR DESCRIPTION
**Pull request by yerke**
I am not sure about details.
@dylanmckay would you be able to help out with them? Does it support core, alloc, or std?

AVR support PR: https://github.com/rust-lang/rust/pull/69478

### CODE REVIEW

**Comment by yerke** [comment]
I looked over https://github.com/avr-rust organization repos and linked projects, and I couldn't find anything referring alloc. My guess so far is that is should be core only `*`.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Comment by shepmaster** [comment]
Right now, AVR doesn’t even compile libcore or compiler_builtins.

**Comment by XAMPPRocky** [comment]
@shepmaster thanks for the clarification I've pushed a fix changing this to a `?`.

**Pull request merged**
