### PR TITLE
document the procedure for adding a new option to rustc

### PR DESCRIPTION
**Pull request by nikomatsakis**
cc @pnkfelix

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I'm going to go ahead and merge this -- it was discussed a few times on Zulip.

**Comment by nikomatsakis** [comment]
[Most recently here](https://zulip-archive.rust-lang.org/131828tcompiler/88059Soyouwanttoaddacompileroption.html)

**Comment by ehuss** [comment]
Would it make sense to move https://rustc-dev-guide.rust-lang.org/cli.html into this document, or maybe link between them?  I would lean towards having the information (guidelines for new CLI options) in one place.

**Comment by nikomatsakis** [comment]
Heh, this is a perennial debate -- @mark-i-m has been advocating for collapsing everything into rustc-dev-guide, but @spastorino and I have been feeling like we'd prefer to separate out "team procedure" from "how to modify the code". Certainly links between them make sense in any case.

**Pull request merged**
